### ISSUE TITLE
next.js | Error: Cannot find module '@tailwindcss/forms' 

### ISSUE THREAD

**Issue by fabmade** [tailwindlabs/tailwindcss-forms#139]
### What version of @tailwindcss/forms are you using?

v0.5.3

### What version of Node.js are you using?

18

### What browser are you using?

Chrom

### What operating system are you using?

alpine

### Reproduction repository

-

### Describe your issue

If i add the @tailwindcss/forms to the devDependencies i will get this error on production. This will not happen, if i add it to the dependencies section.
`
Error: Cannot find module '@tailwindcss/forms'
--
Thu, Jul 6 2023 9:47:50 am | Require stack:
Thu, Jul 6 2023 9:47:50 am | - /app/build/server/pages/producer/[producer]/shop.js
Thu, Jul 6 2023 9:47:50 am | - /app/node_modules/next/dist/server/require.js
Thu, Jul 6 2023 9:47:50 am | - /app/node_modules/next/dist/server/next-server.js
Thu, Jul 6 2023 9:47:50 am | - /app/node_modules/next/dist/server/next.js
Thu, Jul 6 2023 9:47:50 am | - /app/node_modules/next/dist/server/lib/start-server.js
Thu, Jul 6 2023 9:47:50 am | - /app/node_modules/next/dist/cli/next-start.js
Thu, Jul 6 2023 9:47:50 am | - /app/node_modules/next/dist/lib/commands.js
Thu, Jul 6 2023 9:47:50 am | - /app/node_modules/next/dist/bin/next
Thu, Jul 6 2023 9:47:50 am | at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
Thu, Jul 6 2023 9:47:50 am | at mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:23:32)
Thu, Jul 6 2023 9:47:50 am | at Module._load (node:internal/modules/cjs/loader:922:27)
Thu, Jul 6 2023 9:47:50 am | at Module.require (node:internal/modules/cjs/loader:1143:19)
Thu, Jul 6 2023 9:47:50 am | at require (node:internal/modules/cjs/helpers:110:18)
Thu, Jul 6 2023 9:47:50 am | at 9920 (/app/build/server/pages/producer/[producer]/shop.js:1273:18)
Thu, Jul 6 2023 9:47:50 am | at __webpack_require__ (/app/build/server/webpack-runtime.js:25:42)
Thu, Jul 6 2023 9:47:50 am | at 5490 (/app/build/server/pages/producer/[producer]/shop.js:1256:9)
Thu, Jul 6 2023 9:47:50 am | at __webpack_require__ (/app/build/server/webpack-runtime.js:25:42)
Thu, Jul 6 2023 9:47:50 am | at 6903 (/app/build/server/pages/producer/[producer]/shop.js:515:23) {
Thu, Jul 6 2023 9:47:50 am | code: 'MODULE_NOT_FOUND',
Thu, Jul 6 2023 9:47:50 am | requireStack: [
Thu, Jul 6 2023 9:47:50 am | '/app/build/server/pages/producer/[producer]/shop.js',
Thu, Jul 6 2023 9:47:50 am | '/app/node_modules/next/dist/server/require.js',
Thu, Jul 6 2023 9:47:50 am | '/app/node_modules/next/dist/server/next-server.js',
Thu, Jul 6 2023 9:47:50 am | '/app/node_modules/next/dist/server/next.js',
Thu, Jul 6 2023 9:47:50 am | '/app/node_modules/next/dist/server/lib/start-server.js',
Thu, Jul 6 2023 9:47:50 am | '/app/node_modules/next/dist/cli/next-start.js',
Thu, Jul 6 2023 9:47:50 am | '/app/node_modules/next/dist/lib/commands.js',
Thu, Jul 6 2023 9:47:50 am | '/app/node_modules/next/dist/bin/next'
Thu, Jul 6 2023 9:47:50 am | ]
Thu, Jul 6 2023 9:47:50 am | }
`

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction — a [Tailwind Play](https://play.tailwindcss.com) if the issue can be reproduced there, or a GitHub repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
