### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by smith558** [tailwindlabs/tailwindcss-forms#166]
### What version of @tailwindcss/forms are you using?

v0.3.4

### What version of Node.js are you using?

v20.17.0

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### Reproduction repository

N/A (can provide upon request)

### Describe your issue

Getting:
```
TypeError: Cannot read properties of undefined (reading '500')
Occurred while linting /home/stanley/repos/VBD Hub/hub-frontend/tailwind.config.ts:1
Rule: "prettier/prettier"

TypeError: Cannot read properties of undefined (reading '500')
    at /home/stanley/repos/VBD Hub/hub-frontend/node_modules/@tailwindcss/forms/src/index.js:34:63
    at registerPlugins (/home/stanley/repos/VBD Hub/hub-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:815:61)
    at createContext (/home/stanley/repos/VBD Hub/hub-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:1221:5)
    at eY (file:///home/stanley/repos/VBD%20Hub/hub-frontend/node_modules/prettier-plugin-tailwindcss/dist/index.mjs:2353:41224)
    at async b2 (file:///home/stanley/repos/VBD%20Hub/hub-frontend/node_modules/prettier-plugin-tailwindcss/dist/index.mjs:2353:40349)
    at async Object.parse (file:///home/stanley/repos/VBD%20Hub/hub-frontend/node_modules/prettier-plugin-tailwindcss/dist/index.mjs:2353:48339)
    at async parse4 (file:///home/stanley/repos/VBD%20Hub/hub-frontend/node_modules/prettier/index.mjs:20685:11)
    at async coreFormat (file:///home/stanley/repos/VBD%20Hub/hub-frontend/node_modules/prettier/index.mjs:21146:7)
    at async formatWithCursor (file:///home/stanley/repos/VBD%20Hub/hub-frontend/node_modules/prettier/index.mjs:21348:14)
    at async Module.format2 (file:///home/stanley/repos/VBD%20Hub/hub-frontend/node_modules/prettier/index.mjs:22733:25)
Process finished with exit code -1
```

Originating from:
https://github.com/tailwindlabs/tailwindcss-forms/blob/9786ae19f2341dc1540ec7b75bbaa6885ab5dcdf/src/index.js#L40-L42

Which results in:
```
/home/stanley/.nvm/versions/node/v20.17.0/bin/npm run dev

> hub-frontend@0.1.0 dev
> next dev

  ▲ Next.js 14.2.4
  - Local:        http://localhost:3000
  - Environments: .env.local, .env

 ✓ Starting...
 ✓ Ready in 1577ms
 ○ Compiling /conference-liverpool-24 ...
 ⨯ ./app/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[3]!./app/globals.css
TypeError: Cannot read properties of undefined (reading '500')
Import trace for requested module:
./app/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[3]!./app/globals.css
./app/globals.css
 GET /conference-liverpool-24 200 in 2087ms
 ⨯ ./app/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[3]!./app/globals.css
TypeError: Cannot read properties of undefined (reading '500')
Import trace for requested module:
./app/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[3]!./app/globals.css
./app/globals.css
 GET /conference-liverpool-24 500 in 1377ms
```

**Comment by smith558** [comment]
Resolved by upgrading `@tailwindcss/forms`
